theme: jekyll-theme-cayman

title: Pose-guided graph convolutional networks for skeleton-based action recognition
description: A novel multi-modal framework which dynamically fuses the features of pose and skeleton data for improving the action recognition performance of graph convolutional networks.  <br />
