theme: jekyll-theme-cayman

title: Unsupervised domain adaptation based COVID-19 CT infection segmentation network
description: A novel domain adaptation based method proposed for the high-performance segmentation of COVID-19 infection in CT scans even without access to the label.
