theme: jekyll-theme-cayman

title: COVID-19 CT Image Synthesis with a Conditional Generative Adversarial Network
description: A novel COVID-19 CT image synthesis method can generate high-quality synthetic data for downstream diagnostic tasks. (IEEE JBHI featured article.)
